image: registry.michelada.io/financial/creditario-client/ci

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/ruby

before_script:
  - gem install bundler
  - bundle install -j $(nproc) --path vendor

# the 'pages' job will deploy and build your site to the 'public' path
pages:
  stage: deploy
  script:
    - bundle exec sdoc . -T rails --exclude="vendor/|test/"
    - mv doc public
  artifacts:
    paths:
      - public
  only:
    - master # this job will affect only the 'master' branch

test:
  stage: test
  script:
    - bundle exec rake test
  only:
    - branches
  cache:
    untracked: true

lint:
  stage: test
  script:
    - bundle exec rubocop
  only:
    - branches
  cache:
    untracked: true
