name: "Release"

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
          cache-version: 1

      - name: Get tag version
        id: tag_version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Print tag version
        run: echo ${{ steps.tag_version.outputs.VERSION }}

      - name: Build gem
        run: gem build creditario-client.gemspec

      - name: Push gem
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_API_KEY}}"
        run: gem push creditario-client-${{ steps.tag_version.outputs.VERSION}}.gem
